export const questions = [
  {
    id: 1,
    user_id: 1,
    user_char_name: '佐',
    category_id: 1,
    title: '薬の飲み合わせについての相談',
    content: '風邪薬をガン治療中の母に飲ませても大丈夫でしょうか？',
    status: 1,
    created_at: '5分前',
    updated_at: '2022-01-01 00:00:00',
  },
  {
    id: 2,
    user_id: 2,
    user_char_name: '外',
    category_id: 1,
    title: 'テレビのリモコンの使い方がわかりません',
    content: 'リモコンの使い方を教えてください',
    status: 1,
    created_at: '10分前',
    updated_at: '2022-01-01 00:10:00',
  },
  {
    id: 3,
    user_id: 2,
    user_char_name: '外',
    category_id: 1,
    title: 'テレビのリモコンの使い方がわかりません',
    content: 'リモコンの使い方を教えてください',
    status: 1,
    created_at: '10分前',
    updated_at: '2022-01-01 00:10:00',
  }
]